### ISSUE TITLE
How can I use this select2 package in electron app html?

### ISSUE THREAD

**Issue by vidyasagar-r** [select2/docs#17]
I've tried using cdn links, downloaded manually and tried to apply .select2() functionality. Still getting `Uncaught TypeError: $(...).select2 is not a function`

Can you please eloberate the usage?
Thanks in advance

**Comment by TitouanT** [comment]
If you found a solution to your problem please share it.

**Comment by enriquepiatti** [comment]
I have the same issue

**Comment by enriquepiatti** [comment]
OK, here is the solution: https://stackoverflow.com/questions/56871506/how-to-use-select2-with-electron-uncaught-typeerror-select2-is-not-a-fu/56871814#56871814

**Comment by vidyasagar-r** [comment]
> If you found a solution to your problem please share it.

I've not found any solution yet. I'll once I find it @TitouanT

**Comment by vidyasagar-r** [comment]
> OK, here is the solution: https://stackoverflow.com/questions/56871506/how-to-use-select2-with-electron-uncaught-typeerror-select2-is-not-a-fu/56871814#56871814

Thank you @enriquepiatti. Will definitely try this :+1:
