### ISSUE TITLE
Is options document correct?

### ISSUE THREAD

**Issue by yusukesasamo** [select2/docs#19]
I've implemented as same as the following page when I make option group.
https://select2.org/options

But the following error happen.
Uncaught TypeError: Illegal constructor" in jquery.js:1:3233

Then I implemented as like as the following page.
https://select2.org/data-sources/formats
There is no problem.

Do we need `"element": HTMLOptionElement` and `"element": HTMLOptGroupElement`???
If don't need these options, can I modify this page?
https://select2.org/options

**Comment by pedrofurtado** [comment]
@yusukesasamo Please, send a JSFIddle example simulating this scenario. Feel free to reopen the issue.
