### ISSUE TITLE
Setting multiple values does not work as described in documentation

### ISSUE THREAD

**Issue by jahrralf** [select2/docs#31]
I use version 4.0.5.

Page: https://github.com/select2/docs/blob/develop/pages/12.programmatic-control/01.add-select-clear-items/docs.md

It says, which does not work: 
```
$('#mySelect2').val(['1',` '2']);
$('#mySelect2').trigger('change'); // Notify any JS components that the value changed
```

The following works: 
```
      $('#mySelect2').select2('val', ['1', '2']);
```

**Comment by kevin-brown** [comment]
I'm fairly certain that there is no difference, because of how things are implemented under the hood.

https://github.com/select2/select2/blob/6009970b105647fba8448324579944aa4e132b75/src/js/select2/core.js#L570
