### ISSUE TITLE
Wrong link in section Preventing Events

### ISSUE THREAD

**Issue by aurovrata** [select2/docs#5]
I think there is a wrong link to a stackexchange post in the section [Preventing Events](https://select2.org/programmatic-control/events#preventing-events), it currently points to this answer, 

https://stackoverflow.com/a/26706695/2970321 

however, I believe it should point to the next answer, 

https://stackoverflow.com/questions/26705098/jquery-select2-prevent-selecting-in-ajax-response/26706695#36091321

**Comment by alexweissman** [comment]
Thanks!  We should probably remove the link altogether, and just put this explanation directly in the content.

**Comment by aurovrata** [comment]
makes sense.

**Comment by aurovrata** [comment]
I have been experiment with select2 for some time and using it in some projects.  I posted a few solutions to some questions I initially raised on [stackoverflow](https://stackoverflow.com/questions/40807362/preserve-option-class-in-jquery-select2-dropdown-items).  Feel free to use these as examples if useful.

**Comment by alexweissman** [comment]
Yes, it might be worth adding a "Recipes" section to the docs for some common use cases.
